MOCK: True # if true no outgoing call to the cloud is made
HARD_LIMIT: 250 # max allowed spending on google cloud services (in $)

# dirs
DIR_DATA: 'data/'
DIR_SCRIPTS: 'scripts/'

# urls
FASTAPI_URL: 'http://127.0.0.1:8000'

